### ISSUE TITLE
todo на выходные 12-13 октября

### ISSUE THREAD

**Issue by Krethub** [botxme/voenmeh#10]
- [x] Редизайн ленты новостей, при этом логику их открытия оставить неизменной.

- [x] Заменить иконки следующих вкладок: архив, настройки. Сами настройки переименовать в профиль.

- [ ] Переделать шапки во всех вкладках, использовать шрифт TT Commons DemiBold / Bold (сравнить в других сервисах размер и жирность).

- [x] Во вкладках с дедлайнами и архивом добавить соответствующие стикеры: vk.com/sticker/1-14094-512 и vk.com/sticker/1-14090-512
Надпись: Мы активно работаем над развитием этого раздела. Загляните сюда попозже!

- [ ] Во вкладку с архивом добавить ссылку на сайт Военмеха и группы ВКонтакте.
voenmeh.ru – сайт (иконка linked.svg)
vk.com/voenmeh – официальная группа ВКонтакте (иконка logo.svg)
vk.com/voenmehapp – группа сервиса ВКонтакте (иконка logo.svg)

- [ ] Зациклить расписание для группы И-593 до 1 января 2020 года.

- [ ] Светлая тема

**Comment by VBIralo** [comment]
Перемести, пожалуйста, невыполненные таски в другие блоки
